project:
  type: book
  output-dir: docs

html-math-method: mathjax

book:
  title: "Econometrics with Unobserved Heterogeneity"
  author: "Vladislav Morozov"
  date: "2025"
  favicon: favicon.ico
  site-url: https://vladislav-morozov.github.io/econometrics-heterogeneity/
  chapters:
    - index.qmd
    - intro.qmd 
    - syllabus.qmd
    - part: "Linear Models"
      chapters:
        - linear-introduction.qmd
        - linear-within-estimator.qmd
        - linear-dynamic-panel-iv.qmd
        - linear-dynamic-panel-heterogeneity.qmd
        - linear-mean-group.qmd
    - part: "Nonparametrics and Heterogeneity"
    - part: "Quantile and Distributional Methods"
    - references.qmd

bibliography: eco.bib

# execute:
#   freeze: auto  # re-render only when source changes

format:
  html:
    include-in-header: mathjax.html
    theme:
      dark: [themes/ws_dark.scss, themes/block.scss]  
      light: [themes/ws_light.scss, themes/block.scss]



 

