--- 
description: "Learn to  (Lecture Notes)"

open-graph:
    description: "Learn to  (Lecture Notes)"
---
 
# Nonparametric Identification of Quantile Treatment Effects under Unconfoundedness {#sec-qte-id-conf}

::: {.callout-note appearance="simple" icon=false}

## Summary and Learning Outcomes

This section  

By the end of this section, you should be able to:

- Identify 

:::
    
 

## Focus: Distributional Treatment Effects

We retain the (conditional) unconfoundedness assumption ([-@#eq-qte-unconf]).

$$
 \curl{Y_i^x}_x \independent X_i|W_i.
$$ 

## Focus: Quantile Treatment Effects

We now continue 

1. QTE  conditional on $W_i=w$ (@eq-qte-dfn-cond):
$$
\begin{align}
	QTE(x_1, x_2, \tau|w) & = Q_{Y^{x_2}|W}(\tau|w) - Q_{Y^{x_1}|W}(\tau|w).
\end{align}
$$
2. Unconditional QTE (@eq-qte-dfn-uncond):
$$
\begin{aligned}
	QTE(x_1, x_2, \tau ) &  =Q_{Y^{x_2}}(\tau) - 	Q_{Y^{x_1}}(\tau) .
\end{aligned}
$$
3. QTE  conditional on $X_i=x_3$ (@eq-qte-dfn-cond-treat):
$$
\begin{align}
	QTE(x_1, x_2, \tau|x_3) &  =Q_{Y^{x_2}|X}(\tau|x_3) - 	Q_{Y^{x_1}|X}(\tau|x_3) .
\end{align}
$$


As in the previous section, it is sufficient to identify suitable CDFs and quantile functions of $Y^x_i$
 
## Quantile Function Conditional on $W_i$


We begin with the simplest identification argument --- that of the conditional quantiles of $Y^x_i$ given $W_i=w$.

Like in the previous section, we assume that that for all $x$ the conditional CDF of $Y^x_i$ given $W_i=w$ is continuous and strictly increasing. Under these assumptions the conditional quantile $Q_{Y^x|W}(\tau|x)$ uniquely satisfies the following moment condition:

$$
\E\left[ \I\curl{ Y^x_i \leq Q_{Y^x|W}(\tau|w) } |W_i=w\right] =  \tau.
$$

As before, the overall goal is to connect the above moment condition to the the realized outcome $Y_i$. To do so, we first use the unconfoundedness assumption ([-@eq-qte-unconf]) to condition on $X_i=x$:
$$
\begin{aligned}
& \E\left[ \I\curl{ Y^x_i \leq Q_{Y^x|W}(\tau|w) } |W_i=w\right] \\
& =  \E\left[ \I\curl{ Y^x_i \leq Q_{Y^x|W}(\tau|w) } |X_i=x, W_i=w\right].
\end{aligned}
$$
Next, we use that $Y_i=Y^x_i$ if $X_i=x$ to replace $Y^x_i$ with $Y_i$:
$$
\begin{aligned}
&
\E\left[ \I\curl{ Y^x_i \leq Q_{Y^x|W}(\tau|w) } |X_i=x, W_i=w\right] \\
& = \E\left[ \I\curl{ Y_i \leq Q_{Y^x|W}(\tau|w) } |X_i=x, W_i=w\right] .
\end{aligned}
$$
We conclude that $Q_{Y^x|W}(\tau|w)$ must satisfy the moment condition 
$$
\tau = \E\left[ \I\curl{ Y_i \leq Q_{Y^x|W}(\tau|w) } |X_i=x, W_i=w\right].
$$
Here we again observe that the CDF of $Y_i$ given $W_i=w$ and $X_i=x$ is exactly the CDF of $Y^x_i$ given $W_i=w$, and hence strictly increasing and continuous. Let $Q_{Y|X, W}(\tau|x, w)$ be the $\tau$th quantile of $Y_i$ given $\curl{X_i=x, W_i=w}$. By continuity and monotonicity, $Q_{Y|X, W}(\tau|x, w)$ also uniquely satisfies the above moment condition. We conclude the following identification result:
$$
    Q_{Y^x|W}(\tau|w) = Q_{Y|X, W}(\tau|x, w).
$$ {#eq-qte-unconf-cond-w-quant}
In other words, the conditional quantile of potential outcome given covariates is equal to the conditional quantile of the observed outcomes given both covariates and the treatment. 
 
 

## Unconditional Quantile Function


The argument for unconditional quantile $Q_{Y^x}(\tau)$ is more delicate. In contrast to average effects,  we cannot integrate @eq-qte-unconf-cond-w-quant with respect to the marginal distribution of $W_i$ (see @wrn-qte-intro-cond). Instead, identifying $Q_{Y^x}(\tau)$ involves adapting the preceding approach to the unconditional case.
 
As before, we start with the moment condition satisfied by the quantile of interest:
$$
\tau = P(Y^x_i\leq Q_{Y^x}(\tau) ).
$$

??????????????????????

$$
\begin{aligned}
	\tau & = P(Y^x_i\leq Q_{Y^x}(\tau) ) \\
    & =  \E\left[ \I\curl{Y^x_i\leq Q_{Y^x}(\tau)  }\right]\\
    & =  \E\left[ \E\left[ \I\curl{Y^x_i\leq  Q_{Y^x}(\tau)  }|W_i \right]  \right] .
\end{aligned}
$$
We can now apply unconfoundedness inside the conditional expectation to link the moment condition to the observed outcome $Y_i$:
$$
\begin{aligned}
    & \E\left[\E\left[ \I\curl{Y^x_i\leq  Q_{Y^x}(\tau)  }|W_i \right]  \right] \\
    & =   \E\left[ \E\left[\I\curl{Y^x_i\leq Q_{Y^x}(\tau)  }| X_i=x, W_i\right]\right]  \\
	& = \E\left[ \E\left[\I\curl{Y_i\leq Q_{Y^x}(\tau)  }| X_i=x, W_i\right]\right].
\end{aligned}
$$
In principle, we now have obtained a moment condition that characterizes the quantile of interest:
$$
\tau = \E\left[ \E\left[\I\curl{Y_i\leq Q_{Y^x}(\tau)  }| X_i=x, W_i\right]\right].
$$

However, this condition is impractical: it involves iterating an expectation.

Instead, we now develop a more practical characterization where conditioning is limited to propensity scores. To start, we observe that under the event $\curl{X_i=x}$ it holds that $\I\curl{X_i=x}$ is equal to 1. We can then multiply by $\I\curl{X_i=x}$(=1) under the conditional expectation:
$$
    \begin{aligned}
        &  \E\left[ \E\left[\I\curl{Y_i\leq Q_{Y^x}(\tau)  }| X_i=x, W_i\right]\right] \\
        & =  \E\left[ \E\left[\I\curl{X_i=x}\I\curl{Y\leq Q_{Y^x}(\tau) }|X_i=x, W_i\right]\right]
    \end{aligned}
$$ {#eq-qte-uncond-q-interm}

To proceed, we use the following version of the law of total expectations: 

::: {.callout-note appearance="simple"}

If $V, Z$ are random variables and $T$ is a 0/1 random variable, then
$$
\begin{aligned}
 		\E[Z|V]  & =  P(T=1|V) \E[Z|V, T=1] \\
        & \quad   + (1-P(T=1|V)) \E[Z|V, T=0].
\end{aligned}
$$ {#eq-qte-tot-exp}
:::

To apply the above law, we take $T = \I\curl{X_i=x}$ and  $Z = T\I\curl{Y_i\leq Q_{Y^x}(\tau)}$.  By construction, if $T=0$, then $Z=0$, and so the second term in @eq-qte-tot-exp is zero, and hence it holds that
$$
 	\begin{aligned}
 & 		\E\left[\I\curl{X_i=x}\I\curl{Y_i\leq Q_{Y^x}(\tau) }|X_i=x, W_i\right] 
 \\ 
 & = \dfrac{1}{P\left(X_i=x|W_i\right)} \E[\I\curl{X_i=x} \I\curl{Y_i\leq  Q_{Y^x}(\tau) }|W_i].
 	\end{aligned}
$$

We can now insert this characterization back into @eq-qte-uncond-q-interm, and finish the argument as follows:
$$
 \begin{aligned}
  &  \E\left[ \E\left[\I\curl{X_i=x}\I\curl{Y_i\leq Q_{Y^x}(\tau) }|X_i=x, W_i\right]\right]\\
 	& = \E\left[ \dfrac{1}{P\left(X_i=x|W_i\right)} \E[\curl{X_i=x} \I\curl{Y_i\leq  Q_{Y^x}(\tau) }|W_i] \right]\\
 	& =  \E\left[\E\left[  \dfrac{\I\curl{X_i=x}}{P\left(X_i=x|W_i\right)}  \I\curl{Y_i\leq  Q_{Y^x}(\tau) }|W_i\right] \right] \\
 	& = \E\left[  \dfrac{\I\curl{X_i=x} }{P\left(X_i=x|W_i\right)}\I\curl{Y_i\leq Q_{Y^x}(\tau) }\right].
 \end{aligned}
$$
Here we have again used the defining property of conditional expectations, this time to get rid of the internal conditional expectation. 


In summary, we have shown that the unconditional quantile of interest  $Q_{Y^x}(\tau)$ satisfies the following moment condition:
$$
 	 \E\left[  \dfrac{\I\curl{X_i=x} }{P\left(X_i=x|W_i\right)}\I\curl{Y_i\leq Q_{Y^x}(\tau) }\right] = \tau.
$$
This argument is originally due to @Firpo2007EfficientSemiparametricEstimation.


Intuitively, this moment conditions shows that $Q_{Y^x}(\tau)$ is the $\tau$th quantile of a suitably reweighted distribution of the observed outcome. Weighting is done by the inverse of the propensity scores $P(X_i=x|W_i)$, and hence the above result is an instance of identification using inverse probability weighting. 

Note that it is also possible to obtain an IPW expression for $F_{Y^d}(y)$ by proceeding as with $Q_{Y^d}$ starting from the iterated expectation. See @Donald2014EstimationInferenceDistribution.

## Quantile Function Conditional on $X_i$

Last, we focus the conditional quantile function $Q_{Y^x|X}(\tau|x_3)$ — the quantiles of the potential outcome under $x$ in the group which received a potentially different treatment $x_3$. 

To identify these quantiles, we need showcase one more trick: swapping the treatment value in the conditioning set using condition ([-@eq-qte-unconf]). 

To start, rewrite the moment condition $Q_{Y^x|X}(\tau|x_3)$ as before by iterating expectations with respect to $W_i$:
$$
\begin{aligned}
 \tau & =  P\left(Y^x_i \leq Q_{Y^x|X}(\tau|x_3)|X_i=x_3\right)\\
     & =  \E\left[\I\curl{Y^x_i \leq Q_{Y^x|X}(\tau|x_3)}|X_i=x_3 \right]\\
     & = \E\left[  \E\left[\I\curl{Y^x_i \leq Q_{Y^x|X}(\tau|x_3)} |X_i=x_3, W_i\right] |X_i=x_3   \right] .
\end{aligned}
$$

Previously, at this point we would replace $Y^x_i$ by $Y_i$ to continue. However, the conditioning set in the internal expectation specifies that $\curl{X_i=x_3}$, in which case $Y_i$ is actually equal to $Y^{x_3}_i$. 

To resolve this obstacle, observe that by the unconfoundedness assumption ([-@eq-qte-unconf]), conditioning on $X_i$ does not affect the expectation (more precisely, the distribution of the conditional expectation in question). We can then replace $\curl{X_i=x_3}$ with $\curl{X_i=x}$:
$$
\begin{aligned}
  &  \E\left[  \E\left[\I\curl{Y^x_i \leq Q_{Y^x|X}(\tau|x_3)} |X_i=x_3, W_i\right] |X_i=x_3   \right] \\
  & =  \E\left[  \E\left[\I\curl{Y^x_i \leq Q_{Y^x|X}(\tau|x_3)} |X_i=x, W_i\right] |X_i=x_3   \right]\\
  & =  \E\left[  \E\left[\I\curl{Y_i \leq Q_{Y^x|X}(\tau|x_3)} |X_i=x, W_i\right] |X_i=x_3   \right].
\end{aligned}
$$ 
From this point, we can continue
$$
\begin{aligned}
    \tau & =  P\left(Y^x_i \leq Q_{Y^x|X}(\tau|x_3)|X_i=x_3\right)\\
     & =  \E\left[\I\curl{Y^x_i \leq Q_{Y^x|X}(\tau|x_3)}|X_i=x_3 \right]\\
     & = \E\left[  \E\left[\I\curl{Y^x_i \leq Q_{Y^x|X}(\tau|x_3)} |X_i=x_3, W_i\right] |X_i=x_3   \right] \\
          & = \E\left[  \E\left[\I\curl{Y^x_i \leq Q_{Y^x|X}(\tau|x_3)} |X_i=x, W_i\right] |X_i=x_3   \right] \\
          & = \E\left[  \E\left[\I\curl{Y_i \leq Q_{Y^x|X}(\tau|x_3)} |X_i=x, W_i\right] |X_i=x_3   \right]
\end{aligned}
$$	
	
As above, we can write the conditional expectation as 
$$
\begin{aligned}
& \E\left[\I\curl{Y_i \leq Q_{Y^x|X}(\tau|x_3)} |X_i=x, W_i\right] \\
& =  \dfrac{1}{P\left(X_i=x|W_i\right)} \E[\I\curl{X_i=x} \I\curl{Y_i\leq  Q_{Y^x|X}(\tau|x_3) }|W_i].
\end{aligned}
$$

and hence
$$
\begin{aligned}
& \E\left[  \E\left[\I\curl{Y_i \leq Q_{Y^x|X}(\tau|x_3)} |X_i=x, W_i\right] |X_i=x_3   \right] \\
& = \E\left[\dfrac{1}{P\left(X_i=x|W_i\right)} \E[\I\curl{X_i=x} \I\curl{Y_i\leq  Q_{Y^x|X}(\tau|x_3) }|W_i] |X_i=x_3\right] \\
& = \E\left[\E\left[ \dfrac{\I\curl{X_i=x}}{P\left(X_i=x|W_i\right)} \I\curl{Y_i\leq  Q_{Y^x|X}(\tau|x_3) }|W_i\right]   \Bigg|X_i=x_3\right] \\
& = \E\left[ \dfrac{\I\curl{X_i=x}}{P\left(X_i=x|W_i\right)} \I\curl{Y_i\leq  Q_{Y^x|X}(\tau|x_3) }|X_i=x_3\right]
\end{aligned}
$$

 
---

#### Next Section {.unnumbered}

In the next section, we  


$$
\begin{aligned}
    \tau & =  P\left(Y^x_i \leq Q_{Y^x|X, W}(\tau|x_3, w)|X_i=x_3, W_i=w \right)\\
    &  = \E\left[ \I\curl{Y^x_i \leq Q_{Y^x|X, W}(\tau|x_3, w)}| X_i=x_3, W_i=w \right]\\
    & = \E\left[ \I\curl{Y^x_i \leq Q_{Y^x|X, W}(\tau|x_3, w)}| X_i=x, W_i=w \right]\\
    & = \E\left[ \I\curl{Y_i \leq Q_{Y^x|X, W}(\tau|x_3, w)}| X_i=x, W_i=w \right]
\end{aligned}
$$	