--- 
description: "Explore nonparametric models with unobserved heterogeneity. Identification under  minimal functional form assumptions. (Lecture Notes)"

open-graph:
    description: "Explore nonparametric models with unobserved heterogeneity. Identification under minimal functional form assumptions. (Lecture Notes)"
---


# Introduction to Nonparametric Models with Unobserved Heterogeneity {#sec-nonparametric-intro}

::: {.callout-note appearance="simple" icon=false}

## Summary and Learning Outcomes

This section introduces nonparametric models with unobserved heterogeneity and lays out the structure and goals for this block. 

By the end of this section, you should be able to:

- Explain limitations of linear models.   
- Write down generic nonparametric models with unobserved heterogeneity.
- Understand identification challenges and the assumptions commonly used to address them.

:::


## Towards Nonparametric Models

### Motivation

We began these notes by studying linear models with heterogeneous coefficients ([-@eq-lecture_model]), a familiar and flexible starting point. As discussed in section [-@sec-linear-intro], such models are widely used and arise naturally in empirical work.
 
But linearity is not innocent. Except for binary-only covariates, the assumption often lacks theoretical support and may be at odds with the data. Many economic settings suggest richer structures: preferences with satiation, production with non-constant returns to scale, or outcomes bounded by construction. Furthermore, differences between individuals may not be compressible into a finite-dimensional vector of heterogeneous coefficients. 
In such cases, linear models may be severely misspecified and lead to incorrect conclusions. 
 
This motivates a shift. In this block, we move beyond linearity and consider nonparametric models with unobserved heterogeneity — a class that allows for far greater flexibility in how outcomes respond to both observed and unobserved variation. These models present new challenges but also offer a more powerful framework for accounting for unobserved differences. 

### Nonparametric Models


Nonparametric models address functional form concerns directly. Rather than imposing a specific shape on the relationship between $Y$ and the treatments $\bX$, we assume only that this relationship is governed by an unknown function $\phi$ of observed and unobserved variables. This leads to the following general potential outcome models:


- In cross-sectional settings:
$$
	Y_i^{\bx} = \phi(\bx, A_i), \quad {}_{i=1,\dots, N},
$$ {#eq-nonparametric-generic-cross-section}
where $\bX_{i}$ includes the observed variables and $A_i$ includes the unobserved components.

- In panel data settings
$$
 Y_{it}^{\bx} = \phi(\bx, A_i, U_{it}), \quad {}_{i=1,\dots, N}^{t= 1, \dots, T},
$$ {#eq-nonparametric-generic-panel}
where both $A_i$ and $U_{it}$ are not observed. 

Models ([-@eq-nonparametric-generic-cross-section]) and ([-@eq-nonparametric-generic-panel]) parallel and generalize models ([-@eq-cross_sectional_hetero]) and ([-@eq-panel_hetero]).

In both cases the nature of $(A_i, U_{it})$ is not restricted a priori. These unobserved components may include both finite-dimensional vectors (such as unobserved variables or coefficients) and infinite-dimensional objects (such as utility functions). In such a fully unrestricted setting, we can equivalently represent ([-@eq-nonparametric-generic-cross-section]) and ([-@eq-nonparametric-generic-panel]) as
$$
	Y_i^{\bx} = \phi_i(\bx), \quad \quad  Y_{it}^{\bx} = \phi_{it}(\bx),
$$
respectively. 


### Object of Interest


As in the linear case, possible objects of interest include:

-  The full structural function $\phi(\cdot, \cdot)$ or $\phi(\cdot, \cdot, \cdot)$. 	This function fully traces out the potential outcomes  $Y^{\bx}$ for all individuals. 	This corresponds to the problem of identifying individual treatment effects.
- Some distributional features of "treatment effects" — changes in outcomes due to variation in $\bX_{it}$, conditional on unobserved heterogeneity. In the context of model ([-@eq-nonparametric-generic-panel]), these effects are given by
$$
	\begin{aligned}
		&	\phi(\bx_2, A_i, U_{it}) - \phi(\bx_1, A_i, U_{it}),\\
		&	\partial_{\bx} \phi(\bx_0, A_i, U_{it}),
	\end{aligned}
$$    {#eq-nonparametric-effects}
where $\bx_0, \bx_1, \bx_2$ are some possible values for $\bX_{it}$, and the marginal effect is considered if $\phi$ is suitably differentiable in $\bx$.  	The distributional feature of interest may include average effects,   variances, higher-order moments, or the full distribution.

### Common Issue

Unfortunately, models ([-@eq-nonparametric-generic-cross-section]) and ([-@eq-nonparametric-generic-panel]) require further assumptions to be useful, as discussed in section [-@sec-introduction]. Without assumptions, we cannot hope to identify counterfactual objects of interest, not even average effects. 
 
::: {.callout-note appearance="simple" icon=false}

In a strict sense, one may point out that   ([-@eq-nonparametric-generic-cross-section]) and ([-@eq-nonparametric-generic-panel]) are not even models in the sense of offering testable predictions or supporting counterfactual analysis. ([-@eq-nonparametric-generic-cross-section]) and ([-@eq-nonparametric-generic-panel]) are just statements that $\bX$ and $Y$ are related through some function that may differ with $i$ and $t$. Such a statement is vacuously true. For example, without further assumptions one may take $\phi(x, a) = a$ and $A_i = Y_i$ in  ([-@eq-nonparametric-generic-cross-section]). 

:::

Typically, such assumptions fall into two categories:

1. Assumptions on the joint distribution of the observed and the unobserved components, including on the nature of $(A_i, U_{it})$. 
2. Assumptions on how unobserved components enter the equation.

## Models of This Block

To make progress, we focus on two general but tractable versions of the general nonparametric panel model ([-@eq-nonparametric-generic-panel]) in these notes. In both cases, we assume that the outcome $Y_{it}$ is continuous and that $T=2$.

 
### First Model {.unnumbered}

We begin with the following model:
$$
	Y_{it}^{x} = \phi(x, A_i, U_{it}), \quad {}_{i=1, \dots, N}^{t=1, 2}.
$$ {#eq-nonparametric-model-full-nonsep}
where for simplicity we assume that $x$ is scalar. The realized treatment $X_{it}$ is assumed to be continuously distributed, and $\phi$  is continuous in $x$ for all values of $(A_i, U_{it})$. As always, the realized outcomes $Y_{it}$ satisfy
$$
Y_{it} = Y_{it}^{X_{it}} =  \phi(x, A_i, U_{it}), \quad {}_{i=1, \dots, N}^{t=1, 2}.
$$

We consider a version of ([-@eq-nonparametric-model-full-nonsep]) that is very general in terms of unobserved variables $(A_{i}, U_{it})$. In particular, we do not restrict

- The dimension and the form   of $A_i$ and $U_{it}$;
- How the outcome depends on $(A_{i}, U_{it})$;
- The dependence structure between $(A_i, U_{it})$ and $X_{it}$.

At the same time, we impose an assumption of **stationarity** on $U_{it}$.  Its distribution is stable over time conditional on observed and unobserved covariates, allowing us to isolate changes in $Y_{it}$ attributable to variation in $X_{it}$.


### Second Model {.unnumbered}

After reaching the (probable) limits of identification with ([-@eq-nonparametric-model-full-nonsep]),  we consider a different flavor of model ([-@eq-nonparametric-generic-panel]), where the time-varying unobserved component $U_{it}$ is scalar and affects the outcome $Y_{it}$ additively:
$$
Y_{it}^{x} = \phi(x, A_i) + U_{it}, \quad {}_{i=1, \dots, N}^{t=1, 2}
$$ {#eq-nonparametric-model-u-sep}
In contrast to model ([-@eq-nonparametric-model-full-nonsep]), we do not assume that $U_{it}$ is stationary. Models  ([-@eq-nonparametric-model-full-nonsep]) and ([-@eq-nonparametric-model-u-sep]) are hence non-nested. We continue to allow $A_i$ to have unrestricted dimensionality and structure. It may also have a complex dependence structure with $X_{it}$.


## Plan for This Block

In this block, we focus on models ([-@eq-nonparametric-model-full-nonsep])-([-@eq-nonparametric-model-u-sep]) and consider identification of some distributional features of treatment effects ([-@eq-nonparametric-effects]). Specifically,

1. **Average** treatment and marginal **effects** for model ([-@eq-nonparametric-model-full-nonsep]):
   - Show that identifying average effects is more complicated than  considering averages of the outcome directly.
   - Discuss heterogeneity bias, a form and consequence of confounding.
   - Show how stationarity assumptions on $U_{it}$ allow us to identify the average effects for a population of stayers — units with $X_{i1}=X_{i2}$ — without any further assumptions.
   - Consider two generalizations of the identification result: beyond the population of stayers and allowing some non-stationarity in the structural function.
2. **Variance** of treatment and marginal effects in model ([-@eq-nonparametric-model-u-sep]): identify the variance of effects  ([-@eq-nonparametric-effects]) by requiring that $U_{it}$ cannot depend on future values of $\bX_{it}$

 
In the next block, we also revisit model ([-@eq-nonparametric-model-full-nonsep]) through the lens of quantile regression.

## A Brief Classification of Nonparametric Models

In these notes we primarily focus on the general and powerful models ([-@eq-nonparametric-model-full-nonsep])-([-@eq-nonparametric-model-u-sep]). However, much work has gone into analyzing other special instances of ([-@eq-nonparametric-generic-cross-section]) and ([-@eq-nonparametric-generic-panel]). Before moving on to identification of average effects, we offer a brief taxonomy of nonparametric models with unobserved heterogeneity with some essential references. We organize the literature by the types of assumptions made:


- *How unobserved heterogeneity enters in the system*:
  - Fully non-separable models  [@Altonji2005; @Hoderlein2007; @Hoderlein2007; @Chernozhukov2015].
  -  Partially additive separable panel models: [@Chen2003; @Evdokimov2012; @Blundell2012b; @Morozov2023jmp].
    - Fully separable, additively [@Henderson2008NonparametricEstimationTesting; @Boneva2015SemiparametricModelHeterogeneous; @Lee2015PanelNonparametricRegression;@Henderson2024NonparametricModelsFixed] or multiplicatively [@Beckert2008HeterogeneityNonParametricAnalysis].
- *What assumptions are imposed on the form of unobserved components*: restrictions on dimension such as scalarity [@Matzkin2003; @Altonji2005; @Imbens2009]  or no restrictions [@Hoderlein2007; @Hoderlein2007; @Chernozhukov2015]]
- *What assumptions are imposed on dependence structure between observed and unobserved components*: full or partial independence restrictions [@Hoderlein2007; @Imbens2009] vs. no independence restrictions [@Hoderlein2012; @Chernozhukov2015].
- *The nature of the outcome variable*: continuous-outcome models [@Chernozhukov2015] or discrete-outcome models [@Manski1987; @Chesher2017; @Chesher2020].

---

#### Next Section {.unnumbered}

In the next section, we begin our analysis of average effects in model ([-@eq-nonparametric-model-full-nonsep]) and discuss why identification is more complex that analyzing average outcomes.