--- 
description: "Learn why standard IV estimators do not estimate average coefficients in heterogeneous dynamic panel models: theory and an example. (Lecture notes)."
open-graph:
    description: "Learn why standard IV estimators do not estimate average coefficients in heterogeneous dynamic panel models: theory and an example. (Lecture notes)."
---

# Heterogeneous Coefficient Dynamic Panels and Instrumental Variable Estimators

::: {.callout-note appearance="simple" icon=false}

## Summary and Learning Outcomes

This section shows that IV estimators (Anderson-Hsiao, Arellano-Bond, etc.) do not estimate average coefficients in heterogeneous dynamic panel models.

By the end of this section, you should be able to:

- Understand why lagged outcomes are not valid instruments if the coefficients are heterogeneous. 
- Describe the overall challenge of finding valid instruments under 
- Explain why dynamic models with heterogeneous coefficients introduce more challenges than static models. 
 
:::




## Introduction and Model



As in the static case, it is not clear why slopes should be homogenous in dynamic models. If the coefficients are the same between units, all units have the same dynamics. Such an assumption seems rather unrealistic in most scenarios.

As a consequence, we now consider heterogeneous dynamic models. In this section we again focus on a simple AR(1) model with no exogenous regressors. Specifically, we look at the following heterogeneous version of model ([-@eq-dynamic-interlude-dynamic-simple]):
$$
\begin{aligned}
	Y_{it}   & = A_i +  \lambda_i Y_{it-1} + Y_{it}, \\
0 & = \E[Y_{it}| \curl{Y_{is}}_{s\leq t}] .
\end{aligned}
$$  {#eq-dynamic-heterogeneity-model}
This model allows for unit-specific dynamics, as the coefficients $\lambda_i$ can vary across $i$. The above model is also another instance of the general model ([-@eq-lecture_model]). 

As before, we are interested in the average coefficient $\E[\lambda_i]$. 


## Endogeneity due to Heterogeneity
 
Can the IV estimators  of the previous section estimate $\E[\lambda_i]$ under model ([-@eq-dynamic-heterogeneity-model])? Under what conditions?  To answer these questions, recall that the IV estimators of the previous section are based on taking first differences in the model and then using lagged values of $Y_{it}$ as instruments. 

### Endogeneity in Differenced Heterogeneous Equation 
To replicate the procedure, we take differences in @eq-dynamic-heterogeneity-model and write the differenced model as
$$
\begin{aligned}
	\Delta Y_{it} & = \lambda \Delta Y_{it-1} +  V_{it}, \\
	V_{it} & = \eta_i\Delta Y_{it-1} + \Delta U_{it} =0, 
\end{aligned} 
$$ {#eq-dynamic-heterogeneity-differenced}
where we label
$$
\begin{aligned}
 \lambda & = \E[\lambda_i], \\
 \eta_i & = \lambda_i - \lambda. 
\end{aligned}
$$ 


It is easy to check that $\Delta Y_{it-1}$ is still endogenous because it contains $U_{it-1}$, which is correlated with the residual term. The same problematic term  $\lambda \E[U_{it-1}^2]$ is present in $\E[V_{it}\Delta Y_{it-1}]$. 


### Conditions for Instruments

Can we find a suitable instrument for $\Delta Y_{it-1}$? Any valid instrument must satisfy relevance and exogeneity, which now take the following form: 
$$
\begin{aligned} 
	\E[Z_{it}\Delta Y_{it-1}] &  \neq 0 ,\\
	\E[Z_{it} V_{it}] & = \E[ \eta_i Z_{it}\Delta Y_{it-1} ] + \E[Z_{it}U_{it}].
\end{aligned} 
$$
Note that a new $\E[ \eta_i Z_{it}\Delta Y_{it-1} ]$ term now appears in the exogeneity condition. 

### Endogeneity of Lagged Outcomes 

Unlike in the homogeneous case, $Y_{it-2}$ is not a valid instrument anymore. We show that $Y_{it-2}$ is not exogenous in a simple case with the following assumptions:

-  $\abs{\lambda_i}<1$.
-  @eq-dynamic-heterogeneity-model can be extended infinitely far into the past by recursive substitution, so that 
$$
Y_{it} = \dfrac{A_i}{1-\lambda_i} + \sum_{k=0}^{\infty} \lambda_i^k U_{it-k}.
$$
- $\curl{U_{it}}_t$ is an IID sequence with finite second moments, and $U_{it}$ is independent of $(A_i, \lambda_i)$.

Under the above assumptions the first expectation in $\E[Y_{it-2} V_{it}]$ can be evaluated as follows:
$$
\begin{aligned}
& \E[ \eta_i Y_{it-2}\Delta Y_{it-1} ]
\\ 
% & = \E\left[ \eta_i\left( \left(\sum_{k=0}^{\infty} \lambda_i^k u_{i,t-k-1}\right)\left(\sum_{k=0}^{\infty} \lambda_i^k u_{i,t-k-2}\right) - \left(\sum_{k=0}^{\infty} \lambda_i^k u_{i,t-k-2}\right)^2 \right) \right] \\
& = \E\left[ \eta_i\left( \left(\sum_{k=0}^{\infty} \lambda_i^{1+2k} U_{i,t-k-2}^2 \right)  -  \left(\sum_{k=0}^{\infty} \lambda_i^{2k} U^2_{i,t-k-2}\right)  \right)\right] \\
& = \E[U_{it}^2] \E\left[\eta_i (1-\lambda_i) \sum_{k=0}^{\infty} \lambda_i^{2k}   \right].
\end{aligned}
$$
In general, there is no reason to expect the above expectation to be zero if $\eta_i$ is not zero. The second term involves a sum of even-order moments of $\eta_i$ (equivalently, $\lambda_i)$; such a sum would in general be non-zero.

We conclude that 
$$
\E[ \eta_i Y_{it-2}\Delta Y_{it-1} ]\neq 0,
$$
and so in general that 
$$
\E[Y_{it-2} V_{it}]\neq 0.
$$
In other words, $Y_{it-2}$ *is not a valid instrument under the heterogeneous mode*l ([-@eq-dynamic-heterogeneity-model]). The same logic applies under more general assumptions and to higher-order lags of $Y_{it}$.

More broadly, the problem of finding a valid instrument $Z_{it}$ for @eq-dynamic-heterogeneity-differenced appears intractable. The relevance condition requires that $Z_{it}$ be correlated with $\Delta Y_{it-1}$. As a consequence, it is likely that $Z_{it}$ is also correlated with $\eta_i \Delta Y_{it-1}$ (particularly since $\eta_i$ appears inside $\Delta Y_{it-1}$). However, it would then be the case that $\E[ \eta_i Z_{it}\Delta Y_{it-1} ]\neq 0$, and exogeneity would fail. 


We conclude that the IV estimators of the previous section do not consistently estimate $\E[\lambda_i]$, no matter how we choose the instruments, regardless the magnitude of $T$. Moreover, the results of @Pesaran1995 imply that the estimators may converge to any value (not exceeding 1), regardless of the underlying true values of $\E[\lambda_i]$.




### Aside: Regarding Restrictions on Coefficients

There is a further point of contrast with the static case. In section [-@sec-linear-within] we noted that OLS can consistently estimate the average coefficients in a static model if the coefficients $\bbeta_i$ are (mean) independent of the regressors. We also derived a weaker condition for the consistency of the within estimator. 

However, no such independence assumptions are possible in a dynamic model. By construction, the coefficients $(A_i, \lambda_i)$ are directly embedded in the process for the regressor $Y_{it-1}$ through
$$
Y_{it-1} = A_i + \lambda_i Y_{it-2} + U_{it-2}.
$$
As a result, $Y_{it-1}$ and $(A_i, \lambda_i)$ cannot be (mean) independent by construction.


---

#### Next Section {.unnumbered}

In the next section, we study a simple estimator for $\E[\bbeta_i]$ that is robust both to coefficient heterogeneity and dynamics.